// <auto-generated />
using System;
using CitypointTravel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CitypointTravel.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CitypointTravel.Data.Models.Cities", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Citiesid")
                        .HasColumnType("int");

                    b.Property<double>("apartmentCost")
                        .HasColumnType("float");

                    b.Property<double>("cityRating")
                        .HasColumnType("float");

                    b.Property<double>("costOfFood")
                        .HasColumnType("float");

                    b.Property<double>("costOfLiving")
                        .HasColumnType("float");

                    b.Property<double>("distance")
                        .HasColumnType("float");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isFavourite")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pollutionIndex")
                        .HasColumnType("float");

                    b.Property<string>("qualityOfLife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("taxiCost")
                        .HasColumnType("float");

                    b.Property<string>("weather")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Citiesid");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CitypointTravel.Data.Models.Cities", b =>
                {
                    b.HasOne("CitypointTravel.Data.Models.Cities", null)
                        .WithMany("cities")
                        .HasForeignKey("Citiesid");
                });

            modelBuilder.Entity("CitypointTravel.Data.Models.Cities", b =>
                {
                    b.Navigation("cities");
                });
#pragma warning restore 612, 618
        }
    }
}
